name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.x'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build windows --release
      - name: Zip Release
        shell: pwsh
        run: |
          $out = "input-vpn-windows-${env:GITHUB_REF_NAME}.zip"
          Compress-Archive -Path "build\windows\x64\runner\Release\*" -DestinationPath $out
          echo "ASSET_PATH=$out" >> $env:GITHUB_ENV
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ASSET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
